name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build packages
        run: npm run build

      - name: Run tests with AppMap
        run: npx appmap-node npm run test
